name: build bun
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - bun/**
jobs:
  push:
    name: "yolks:bun_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
          - canary
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.qcloud_owner }}
          password: ${{ secrets.qcloud_registry_token }}
      - uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.aliyun_owner }}
          password: ${{ secrets.aliyun_registry_token }}
      - uses: docker/build-push-action@v5
        with:
          context: ./bun
          file: ./bun/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/jiongzu/yolks:bun_${{ matrix.tag }}
            ccr.ccs.tencentyun.com/jiongzu/yolks:bun_${{ matrix.tag }}