name: build pypy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - pypy/**
jobs:
  push:
    name: "yolks:pypy_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '3.10'
          - '3.9'
          - '2.7'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2          
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./pypy
          file: ./pypy/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/parkervcp/yolks:pypy_${{ matrix.tag }}
