name: build steamcmd
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - steamcmd/**
jobs:
  push:
    name: "steamcmd:${{ matrix.distro }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian
          - ubuntu
          - dotnet
          - proton   
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.qcloud_owner }}
          password: ${{ secrets.qcloud_registry_token }}
      - uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.aliyun_owner }}
          password: ${{ secrets.aliyun_registry_token }}
      - uses: docker/build-push-action@v5
        with:
          context: ./steamcmd
          file: ./steamcmd/${{ matrix.distro }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/jiongzu/steamcmd:${{ matrix.distro }}
            ccr.ccs.tencentyun.com/jiongzu/steamcmd:${{ matrix.distro }}
